export interface LandingPage {
  title: string
  description: string
  keywords: string[]
  useCases: string[]
  proofPoints: string[]
  audience: string
}

export const landingPages: Record<string, LandingPage> = {
  "business-loans": {
    title: "Business funding built around your business",
    description: "Compare responsible business funding options through one secure MoneyBee request.",
    keywords: ["business loans", "small business funding", "business financing"],
    useCases: ["Working capital", "Inventory", "Expansion", "Payroll"],
    proofPoints: ["Secure borrower portal", "Clear next steps", "No approval guarantee language"],
    audience: "Small business owners comparing funding options",
  },
  "working-capital": {
    title: "Working capital for everyday business needs",
    description: "Request working capital for cash flow, payroll, supplier costs, and short-term operating needs.",
    keywords: ["working capital loans", "business working capital", "cash flow financing"],
    useCases: ["Payroll", "Marketing", "Supplier costs", "Cash-flow gaps"],
    proofPoints: ["Fast intake", "Document checklist", "Human review"],
    audience: "Operators managing day-to-day cash flow",
  },
  "business-line-of-credit": {
    title: "Business line of credit options",
    description: "Explore revolving credit options for seasonal needs, purchasing, and ongoing projects.",
    keywords: ["business line of credit", "revolving business credit", "small business credit line"],
    useCases: ["Seasonal needs", "Purchasing", "Projects", "Emergencies"],
    proofPoints: ["Reusable application record", "Requirement tracking", "Secure account access"],
    audience: "Businesses that need flexible access to capital",
  },
  "equipment-financing": {
    title: "Equipment financing without draining cash",
    description: "Finance vehicles, machinery, technology, and fixtures while preserving operating cash.",
    keywords: ["equipment financing", "business equipment loan", "equipment lease financing"],
    useCases: ["Vehicles", "Machinery", "Technology", "Fixtures"],
    proofPoints: ["Use-of-funds capture", "Document upload workflow", "Offer review controls"],
    audience: "Businesses buying or replacing essential equipment",
  },
  "sba-loans": {
    title: "SBA loan guidance and funding review",
    description: "Learn whether an SBA-related option may fit your longer-term business plans.",
    keywords: ["SBA loans", "SBA business loan", "long term business financing"],
    useCases: ["Expansion", "Acquisition", "Real estate", "Refinancing"],
    proofPoints: ["Eligibility guidance", "Requirement snapshots", "Disclosure-first flow"],
    audience: "Business owners planning larger or longer-term financing",
  },
  "fast-business-funding": {
    title: "Fast business funding request",
    description: "Start a secure request when your business needs a responsible funding review quickly.",
    keywords: ["fast business funding", "quick business loan", "same day business funding"],
    useCases: ["Urgent inventory", "Repairs", "Payroll", "Opportunity"],
    proofPoints: ["Immediate reference number", "Idempotent forms", "Controlled lender delivery"],
    audience: "Businesses with time-sensitive funding needs",
  },
  "restaurant-financing": {
    title: "Restaurant financing for busy operators",
    description: "Request capital for restaurant equipment, renovation, inventory, staffing, and expansion.",
    keywords: ["restaurant financing", "restaurant business loan", "food service funding"],
    useCases: ["Equipment", "Renovation", "Inventory", "Expansion"],
    proofPoints: ["Industry-specific intake", "Revenue review", "Secure documents"],
    audience: "Restaurant, cafe, food truck, and food service owners",
  },
  "trucking-business-loans": {
    title: "Trucking business loans and fleet financing",
    description: "Explore financing for truck purchases, repairs, fuel, insurance, and fleet operations.",
    keywords: ["trucking business loans", "fleet financing", "commercial truck financing"],
    useCases: ["Truck purchase", "Repairs", "Fuel", "Insurance"],
    proofPoints: ["Vehicle use case capture", "Bank evidence review", "Lender workspace"],
    audience: "Owner-operators and fleet businesses",
  },
  "construction-business-loans": {
    title: "Construction business funding",
    description: "Request financing around project cash flow, materials, payroll, equipment, and bonding needs.",
    keywords: ["construction business loans", "contractor financing", "construction working capital"],
    useCases: ["Materials", "Payroll", "Equipment", "Bonding"],
    proofPoints: ["Project-oriented intake", "Condition tracking", "Document evidence"],
    audience: "Contractors and construction businesses",
  },
  "retail-business-loans": {
    title: "Retail business loans for inventory and growth",
    description: "Explore capital for inventory, renovations, marketing, and new retail locations.",
    keywords: ["retail business loans", "inventory financing", "store expansion funding"],
    useCases: ["Inventory", "Renovation", "Marketing", "New location"],
    proofPoints: ["Seasonal needs support", "Offer comparison", "Secure portal"],
    audience: "Retail stores and ecommerce businesses",
  },
  "merchant-cash-advance": {
    title: "Merchant cash advance review",
    description: "Understand revenue-based funding options and review costs before making a decision.",
    keywords: ["merchant cash advance", "revenue based financing", "business cash advance"],
    useCases: ["Card-sales businesses", "Short-term needs", "Inventory", "Repairs"],
    proofPoints: ["Cost disclosure focus", "No hidden approval promise", "Evidence-based review"],
    audience: "Businesses evaluating revenue-based financing",
  },
  "invoice-financing": {
    title: "Invoice financing for unpaid receivables",
    description: "Request a review for financing tied to outstanding invoices and customer receivables.",
    keywords: ["invoice financing", "accounts receivable financing", "invoice factoring"],
    useCases: ["Unpaid invoices", "Slow receivables", "Payroll", "Supplier payments"],
    proofPoints: ["Receivable context", "Document checklist", "Controlled review"],
    audience: "B2B businesses waiting on customer payments",
  },
  "commercial-real-estate-loans": {
    title: "Commercial real estate loan options",
    description: "Explore funding for owner-occupied property, expansion, renovation, and refinance needs.",
    keywords: ["commercial real estate loans", "CRE financing", "business property loan"],
    useCases: ["Owner-occupied property", "Renovation", "Expansion", "Refinance"],
    proofPoints: ["Longer-term review", "Requirement snapshots", "Audit trail"],
    audience: "Businesses financing commercial property",
  },
  "medical-practice-financing": {
    title: "Medical practice financing",
    description: "Capital review for healthcare practices investing in equipment, staffing, and growth.",
    keywords: ["medical practice financing", "healthcare business loans", "practice acquisition financing"],
    useCases: ["Equipment", "Staffing", "Practice acquisition", "Expansion"],
    proofPoints: ["Professional-service intake", "Secure records", "Clear conditions"],
    audience: "Medical, dental, and healthcare practice owners",
  },
  "beauty-salon-financing": {
    title: "Salon and spa business financing",
    description: "Request funding for salon equipment, renovation, inventory, hiring, and growth plans.",
    keywords: ["salon financing", "spa business loan", "beauty business funding"],
    useCases: ["Chairs and fixtures", "Renovation", "Inventory", "Hiring"],
    proofPoints: ["Simple intake", "Revenue review", "Portal updates"],
    audience: "Salon, spa, and beauty business owners",
  },
  "franchise-financing": {
    title: "Franchise financing review",
    description: "Explore funding for franchise startup costs, expansion, remodels, and operating capital.",
    keywords: ["franchise financing", "franchise business loan", "franchise working capital"],
    useCases: ["Startup costs", "Remodel", "Expansion", "Operating capital"],
    proofPoints: ["Brand/location context", "Document workflow", "Offer controls"],
    audience: "Franchise owners and operators",
  },
  "startup-business-loans": {
    title: "Startup business funding review",
    description: "Start a responsible funding request for newer businesses and early operating needs.",
    keywords: ["startup business loans", "startup funding", "new business financing"],
    useCases: ["Launch costs", "Inventory", "Marketing", "Equipment"],
    proofPoints: ["Eligibility clarity", "No guarantee claims", "Human follow-up"],
    audience: "Newer businesses exploring financing",
  },
  "minority-business-loans": {
    title: "Business funding for diverse founders",
    description: "Submit one secure request to explore business financing options for growth and stability.",
    keywords: ["minority business loans", "diverse founder funding", "small business financing"],
    useCases: ["Working capital", "Hiring", "Equipment", "Expansion"],
    proofPoints: ["Accessible intake", "Clear disclosures", "Equal review standards"],
    audience: "Diverse founders and small business owners",
  },
  "women-owned-business-loans": {
    title: "Funding for women-owned businesses",
    description: "Explore financing options for women-owned businesses through a secure MoneyBee request.",
    keywords: ["women owned business loans", "women entrepreneur funding", "small business loans for women"],
    useCases: ["Expansion", "Inventory", "Payroll", "Equipment"],
    proofPoints: ["Secure application", "Requirement visibility", "Responsible review"],
    audience: "Women-owned businesses and entrepreneurs",
  },
  "bad-credit-business-loans": {
    title: "Business funding review with credit challenges",
    description: "Request a careful review when your business has revenue but credit history is complicated.",
    keywords: ["bad credit business loans", "business funding with bad credit", "alternative business financing"],
    useCases: ["Cash-flow repair", "Inventory", "Emergency costs", "Debt planning"],
    proofPoints: ["Credit authorization first", "Transparent blockers", "No guaranteed approval"],
    audience: "Businesses with imperfect credit histories",
  },
}

export const financingSlugs = Object.keys(landingPages)
