export type MoneyBeeErrorBody={error:{code:string;title:string;detail:string;request_id:string|null;retryable:boolean;context:Record<string,unknown>;}};
export class MoneyBeeApiError extends Error{constructor(public readonly status:number,public readonly body:MoneyBeeErrorBody){super(body.error.detail);}}
export type ApiResponse<T>={data:T;etag:string|null;requestId:string|null;correlationId:string|null;};
export type TokenProvider=()=>Promise<string|null>;
let tokenProvider:TokenProvider=async()=>null;
export function setTokenProvider(provider:TokenProvider):void{tokenProvider=provider;}
function id():string{return crypto.randomUUID();}
export async function api<T>(path:string,options:RequestInit&{ifMatch?:string;idempotencyKey?:string;correlationId?:string;}={}):Promise<ApiResponse<T>>{const token=await tokenProvider();const requestId=id();const correlationId=options.correlationId??id();const headers=new Headers(options.headers);if(!(options.body instanceof FormData)&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");headers.set("X-Request-ID",requestId);headers.set("X-Correlation-ID",correlationId);if(token)headers.set("Authorization",`Bearer ${token}`);if(options.ifMatch)headers.set("If-Match",options.ifMatch);if(options.idempotencyKey)headers.set("Idempotency-Key",options.idempotencyKey);const response=await fetch(`${import.meta.env.VITE_API_BASE_URL??"http://localhost:8000"}/api/v2${path}`,{...options,headers});if(!response.ok){let body:MoneyBeeErrorBody;try{body=await response.json();}catch{body={error:{code:"UNEXPECTED_RESPONSE",title:"Unexpected API response",detail:`HTTP ${response.status}`,request_id:response.headers.get("X-Request-ID"),retryable:response.status>=500,context:{}}};}throw new MoneyBeeApiError(response.status,body);}const data=response.status===204?undefined as T:await response.json() as T;return{data,etag:response.headers.get("ETag"),requestId:response.headers.get("X-Request-ID"),correlationId:response.headers.get("X-Correlation-ID")};}
export function createIdempotencyKey():string{return crypto.randomUUID();}
